const BOARD_SIZE_FACTOR = 0.75
const BUTTON_SIZE = 0.08
const BUTTON_PADDING = 0.01
const GRID_SIZE = 7
const BUTTON_STEP = BUTTON_PADDING + BUTTON_SIZE
const GRID_SPACE = 0.2

const NEXT_GRID_START = GRID_SPACE+GRID_SIZE*BUTTON_STEP

const INITIAL_X = 0.15
const INITIAL_Y = 0.3

TEAM_COLOURS = ["CORNFLOWERBLUE", "ORANGERED"]